buildscript {
    ext {
        compile_sdk = 34
        min_sdk = 24
        target_sdk = 34
    }
}

plugins {
    id 'com.android.application' version '8.2.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.20' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
